### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by natrius** [Cadair/octoprint-matrix-notifier-plugin#14]
Hey, 

as i was starting with OctoPrint i was researching for Matrix messaging and found this. Last change was instructions on readme on April 2021 . I found another one - Octoslack https://github.com/fraschetti/Octoslack but it seems more outdated and not working with matrix at all. 

So, the question is: Do you still maintain this plugin? :)

Thanks for your work so far!

**Comment by Cadair** [comment]
I have just pushed a release (at long last), just in time for octoprint 1.9 to completely rework the webcam stuff :worried:
