### ISSUE TITLE
Image flip settings are not respected

### ISSUE THREAD

**Issue by nmaggioni** [Cadair/octoprint-matrix-notifier-plugin#7]
Pictures attached to messages do not respect the image rotation settings specified in OctoPrint (_Settings > Webcam & Timelapse > Flip webcam horizontally/vertically_).

Probably [the same approach taken by OctoPrint-Telegram](https://github.com/fabianonline/OctoPrint-Telegram/blob/e9ac3c5bf98e0b1ee4b5710c126a0204cae2e36c/octoprint_telegram/__init__.py#L2557) could be used, their image grabbing handler isn't much different.

**Comment by Cadair** [comment]
Should be fixed by #13 and released in 0.3
