### ISSUE TITLE
No Progress Message sent

### ISSUE THREAD

**Issue by GrollTroll** [Cadair/octoprint-matrix-notifier-plugin#8]
Great plugin!

The events _"Print started"_ and _"Print Done"_ arrive, but unfortunately the _"Fortschritt"_ (forgot the translation? :D) not. I haven't tried or had the other two events yet. I entered "10" as the value for _"Progress Interval Percent"_. Shouldn't a message then be sent at 10%, 20%, etc.? Or do I misunderstand the input format? Maybe I did something else wrong, any hint?

Thank you :D

**Comment by Cadair** [comment]
Weird, that should work, can you see anything in the logs that would explain why it is breaking?

**Comment by joiyco** [comment]
I have the same issue,
 here the needed part of the logfile
`2021-08-24 12:28:16,661 - octoprint.printer.standard - ERROR - Exception while sending print progress to plugin matrix_notifier
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/printer/standard.py", line 347, in call_plugins
    plugin.on_print_progress(storage, filename, progress)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1941, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_matrix_notifier/plugin.py", line 220, in on_print_progress
    if not progress or not(progress / interval == progress // interval) or progress == 100:
TypeError: unsupported operand type(s) for /: 'int' and 'str'
`

**Comment by Cadair** [comment]
Oh! That's weird.

Did you configure the interval with the web ui?

**Comment by Cadair** [comment]
I don't have time to fix this today, but if someone else wants to make a PR the fix should just be putting `int()` around the read from the config variable here: https://github.com/Cadair/octoprint-matrix-notifier-plugin/blob/main/octoprint_matrix_notifier/plugin.py#L216

**Comment by joiyco** [comment]
yes I did. I also reinstelled it and tryed to modify the script on my but did'nt get It work. So again reinstalled.

By the way thank you for the great plugin.

**Comment by joiyco** [comment]
> I don't have time to fix this today, but if someone else wants to make a PR the fix should just be putting `int()` around the read from the config variable here: https://github.com/Cadair/octoprint-matrix-notifier-plugin/blob/main/octoprint_matrix_notifier/plugin.py#L216

I trieda view different thinks in the try and error principle but couldn't get it Work.

**Comment by joiyco** [comment]
#10 will fix the issue.

**Comment by Cadair** [comment]
I just pushed 0.2.2, so you should be able to update and get the fix. Let me know if you run into any more issues, and thanks to @joiyco for the PR :)

**Comment by joiyco** [comment]
@Cadair no problem after the current print is finished I will update the Plugin and let you know if it worked. 

Wish I could do more.
